### ISSUE TITLE
Contact Center Blog S3 URL does not exist. CloudFormation Fails to execute.

### ISSUE THREAD

**Issue by taylanu** [amazon-connect/advanced-usage-analytics#3]
The source bucket for aws-contact-center-blog/usage-analytics either does not exist or has been moved. 
Access denied error thrown when trying to launch stack from blog: https://aws.amazon.com/blogs/contact-center/analyzing-amazon-connect-usage-with-agent-desktop-and-streaming-data/
As well as from the "cloudformation" folder.

**Comment by virtualgill** [comment]
Hi @taylanu - apologies for the delay on this one, you should be able to access those files now
